update boost to 1.57
current boost library 1.50 will cause an error C2228. using the update
boost library 1.57 will resolve this error and able to debug AL smoothly